### ISSUE TITLE
Error in Validating Resource (559) 

### ISSUE THREAD

**Issue by hirdajoe** [jumpinjackie/mapguide-maestro#63] opened 2018-04-28 06:36 UTC
Hi, I have problem whenever I need to save the customization of a layer,
It returns error like this:

********************************************************************************
Validating resource: Session:af53742a-4aac-11e8-8000-1008b1f1f8b9_en_MTI3LjAuMC4x0AFC0AFB0AFA//4475dcd5-e409-471d-9dea-104b437582c1.LayerDefinition
Error - Error_General_ValidationError: Failed in validator: 
	The remote server returned an error: (559) MgInvalidRepositoryTypeException.: 
Invalid repository type.

- MgResourceServiceHandler.ProcessOperation() line 80 file c:\working\build_area\mapguide\2.6.0\x64\mgdev\server\src\services\resource\ResourceServiceHandler.cpp
- MgOpGetResourceHeader.Execute() line 97 file c:\working\build_area\mapguide\2.6.0\x64\mgdev\server\src\services\resource\OpGetResourceHeader.cpp
- MgServerResourceService.GetResourceHeader() line 1304 file c:\working\build_area\mapguide\2.6.0\x64\mgdev\server\src\services\resource\ServerResourceService.cpp

	The remote server returned an error: (559) MgInvalidRepositoryTypeException.

Can anyone help me with this?
Thanks.
Hirda.

**Comment by jumpinjackie** [comment] 2018-04-29 07:15
Duplicate of #58 

As a short-term workaround, turn off "Validate on Save" until the next release that will have a fix for this.

**Closed by jumpinjackie** 2018-04-29 07:15 UTC
